name: Celso Dantas
description: A blog about my studies and findings
meta_description: "My name is Celso Dantas, and this is my blog."

markdown: redcarpet
pygments: true
logo: false
paginate: 15

excerpt_separator: "excerpt_separator"

# Details for the RSS feed generator
url:            'www.celsodantas.com'
author:         'Celso Dantas'
