name: Fernanda Dantas
description: This is my web page =)
meta_description: "My name is Fernanda Dantas and I'm an Architect."

markdown: redcarpet
pygments: true
logo: false
paginate: 15

excerpt_separator: "<!-- more -->"

# Details for the RSS feed generator
url:    'www.fernandadantas.com'
author: 'Fernanda Dantas'

# Disqus Comments
disqus_shortname: "fernandadantasblog"
